# Generated by Django 4.0.3 on 2022-05-18 13:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HabitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('repetition', models.IntegerField()),
                ('number_completed', models.IntegerField(default=0)),
                ('duration', models.IntegerField()),
                ('frequency', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('start_date', models.DateField(default=datetime.datetime(2022, 5, 18, 13, 22, 38, 240502, tzinfo=utc))),
                ('finish_date', models.DateField(default=datetime.datetime(2022, 5, 18, 13, 22, 38, 240502, tzinfo=utc))),
                ('broken', models.BooleanField(default=False)),
                ('streak', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'habit',
            },
        ),
    ]
