# Generated by Django 4.0.3 on 2022-05-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HabitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('repeatition', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('duration_type', models.CharField(max_length=255)),
                ('completed', models.BooleanField()),
                ('start_date', models.DateField()),
                ('finnish_date', models.DateField()),
                ('broken', models.BooleanField()),
                ('streak', models.IntegerField()),
            ],
            options={
                'db_table': 'habit',
            },
        ),
    ]
