# Generated by Django 4.0.3 on 2022-05-18 13:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitmodel',
            name='frequency',
        ),
        migrations.AlterField(
            model_name='habitmodel',
            name='duration',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='habitmodel',
            name='finish_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 18, 13, 37, 5, 230372, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='habitmodel',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 18, 13, 37, 5, 230372, tzinfo=utc)),
        ),
    ]
