# Generated by Django 4.0.5 on 2022-06-28 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_alter_habitmodel_finish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitmodel',
            name='duration',
            field=models.CharField(choices=[('DAILY', 'DAILY'), ('WEEKLY', 'WEEKLY')], default='DAILY', max_length=255),
        ),
        migrations.AlterField(
            model_name='habitmodel',
            name='finish_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='habitmodel',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('task_date', models.DateTimeField()),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habit.habitmodel')),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
