# Generated by Django 4.0.5 on 2022-06-29 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0005_alter_task_task_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='TaskModel',
        ),
        migrations.RemoveField(
            model_name='habitmodel',
            name='repetition',
        ),
    ]
