# Generated by Django 4.0.6 on 2022-07-21 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0007_remove_habitmodel_number_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='completed',
            new_name='done',
        ),
    ]
